# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0SRhpG-Eyfwpn1eaQymonpHbmHs-cEn
"""

import streamlit as st
import random

# ส่วนที่ 1: ตั้งชื่อหัวข้อและแสดงข้อความ
st.title('Test Streamlit')
st.write('Hello World!')

# ส่วนที่ 2: สร้างปุ่มกดเพื่อสุ่มตัวเลข
if st.button('Generate Random Number'):
    random_number = random.randint(1, 100)
    st.write(f'Random Number: {random_number}')